CREATE TABLE MARCA
(
    ID        INT PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL
);

CREATE TABLE MODELO
(
    ID        INT PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL,
    ID_MARCA  INT          NOT NULL,
    FOREIGN KEY (ID_MARCA) REFERENCES MARCA (ID)
);

CREATE TABLE AUTOMOVEL
(
    ID                  INT PRIMARY KEY,
    CHASSI              VARCHAR(250),
    PLACA               VARCHAR(20) NOT NULL,
    QUILOMETROS_RODADOS NUMBER(19),
    ID_MODELO           INT         NOT NULL,
    FOREIGN KEY (ID_MODELO) REFERENCES MODELO (ID)
);

CREATE TABLE ESTADO
(
    ID        INT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    SIGLA     VARCHAR(3)   NOT NULL
);

CREATE TABLE CIDADE
(
    ID        INT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    ID_ESTADO INT          NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID)
);

CREATE TABLE USUARIO
(
    ID        INT PRIMARY KEY,
    NOME      VARCHAR(250) NOT NULL,
    EMAIL     VARCHAR(100) NOT NULL,
    ID_CIDADE INT          NOT NULL,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID)
);

CREATE TABLE EQUIPAMENTO
(
    ID         INT PRIMARY KEY,
    DESCRICAO  VARCHAR(250) NOT NULL,
    DISPONIVEL INT          NOT NULL
);

CREATE TABLE EMPRESTIMO
(
    ID                    INT PRIMARY KEY NOT NULL,
    FINALIDADE            VARCHAR(500)    NOT NULL,
    DT_RETIRADA           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO_REQUISITOR INT             NOT NULL,
    FOREIGN KEY (ID_USUARIO_REQUISITOR) REFERENCES USUARIO (ID)
);

CREATE TABLE EMPRESTIMO_EQUIPAMENTO
(
    ID_EQUIPAMENTO        INT NOT NULL,
    ID_EMPRESTIMO         INT NOT NULL,
    DT_PREVISAO_DEVOLUCAO TIMESTAMP,
    DT_DEVOLUCAO          TIMESTAMP,
    primary key (ID_EQUIPAMENTO, ID_EMPRESTIMO),
    FOREIGN KEY (ID_EMPRESTIMO) REFERENCES EMPRESTIMO (ID),
    FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO (ID)
);

CREATE TABLE PECA
(
    ID        INT PRIMARY KEY,
    DESCRICAO VARCHAR(200)   NOT NULL,
    VALOR     NUMERIC(19, 2) NOT NULL
);

CREATE TABLE VISTORIA
(
    ID           INT PRIMARY KEY,
    DT_VISTORIA  TIMESTAMP NOT NULL,
    ID_AUTOMOVEL INT       NOT NULL,
    ID_USUARIO   INT       NOT NULL,
    FOREIGN KEY (ID_AUTOMOVEL) REFERENCES AUTOMOVEL (ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID)
);

CREATE TABLE AVARIA
(
    ID        INT PRIMARY KEY,
    DT_AVARIA TIMESTAMP NOT NULL,
    ID_PECA   INT       NOT NULL,
    FOREIGN KEY (ID_PECA) REFERENCES PECA (ID)
);
